import type {
  Exercise,
  WorkoutTemplate,
  WorkoutSession,
  PersonalRecord,
  UserProfile,
  MuscleActivation,
  MuscleDetail,
  VolumeDataPoint,
  LiftProgressPoint,
  MuscleVolumeData,
  TrainingRecommendation,
} from "@/types";

// ─── Exercise Library ─────────────────────────────────────────────────────────

export const EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    category: "chest",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "chest", activationType: "primary", intensity: 10 },
      { muscleId: "front-delts", activationType: "secondary", intensity: 6 },
      { muscleId: "triceps", activationType: "secondary", intensity: 6 },
    ],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Lie flat on a bench with feet planted firmly on the floor.",
      "Grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and lower it to your mid-chest in a controlled manner.",
      "Press the bar up explosively until arms are fully extended.",
      "Squeeze your chest at the top before lowering again.",
    ],
    tips: ["Keep shoulder blades retracted throughout the movement.", "Drive your feet into the floor for full-body tension."],
    commonMistakes: ["Flaring elbows too wide", "Bouncing the bar off the chest", "Lifting hips off the bench"],
    variants: ["Incline Bench Press", "Decline Bench Press", "Dumbbell Bench Press"],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "chest",
    equipment: ["dumbbell"],
    muscleMap: [
      { muscleId: "chest", activationType: "primary", intensity: 9 },
      { muscleId: "front-delts", activationType: "secondary", intensity: 7 },
      { muscleId: "triceps", activationType: "secondary", intensity: 5 },
    ],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Set the bench to a 30–45 degree incline.",
      "Hold a dumbbell in each hand at chest level.",
      "Press the dumbbells up and slightly inward until arms are extended.",
      "Lower slowly back to the starting position.",
    ],
    tips: ["Focus on upper chest contraction.", "Don't lock out elbows fully at the top."],
    commonMistakes: ["Setting bench angle too high (shoulder dominant)", "Using too heavy a weight"],
    variants: ["Flat Dumbbell Press", "Cable Fly"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    category: "back",
    equipment: ["bodyweight"],
    muscleMap: [
      { muscleId: "lats", activationType: "primary", intensity: 10 },
      { muscleId: "biceps", activationType: "secondary", intensity: 7 },
      { muscleId: "rear-delts", activationType: "secondary", intensity: 5 },
      { muscleId: "rhomboids", activationType: "secondary", intensity: 5 },
    ],
    movementPattern: "pull",
    difficulty: "intermediate",
    instructions: [
      "Hang from a bar with a slightly wider than shoulder-width overhand grip.",
      "Pull your body up until your chin clears the bar.",
      "Lower yourself in a controlled manner to full arm extension.",
    ],
    tips: ["Initiate with your lats, not your arms.", "Keep core tight throughout."],
    commonMistakes: ["Using momentum/kipping", "Not reaching full extension at the bottom"],
    variants: ["Chin-Up", "Lat Pulldown", "Assisted Pull-Up"],
  },
  {
    id: "barbell-row",
    name: "Barbell Bent-Over Row",
    category: "back",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "lats", activationType: "primary", intensity: 9 },
      { muscleId: "rhomboids", activationType: "primary", intensity: 8 },
      { muscleId: "rear-delts", activationType: "secondary", intensity: 6 },
      { muscleId: "biceps", activationType: "secondary", intensity: 5 },
      { muscleId: "lower-back", activationType: "secondary", intensity: 6 },
    ],
    movementPattern: "pull",
    difficulty: "intermediate",
    instructions: [
      "Stand with feet shoulder-width apart, bar over mid-foot.",
      "Hinge at the hips until torso is roughly parallel to the floor.",
      "Pull the bar to your lower chest/upper abdomen.",
      "Lower the bar under control.",
    ],
    tips: ["Keep your back neutral — no rounding.", "Lead with your elbows, not your hands."],
    commonMistakes: ["Rounding the lower back", "Standing too upright", "Using too much momentum"],
    variants: ["Dumbbell Row", "Seated Cable Row", "T-Bar Row"],
  },
  {
    id: "squat",
    name: "Barbell Back Squat",
    category: "legs",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "quads", activationType: "primary", intensity: 10 },
      { muscleId: "glutes", activationType: "primary", intensity: 8 },
      { muscleId: "hamstrings", activationType: "secondary", intensity: 5 },
      { muscleId: "lower-back", activationType: "secondary", intensity: 5 },
      { muscleId: "abs", activationType: "secondary", intensity: 4 },
    ],
    movementPattern: "squat",
    difficulty: "advanced",
    instructions: [
      "Position bar on upper traps in a high-bar position.",
      "Stand with feet slightly wider than shoulder-width, toes slightly out.",
      "Break at hips and knees simultaneously, descending until thighs are parallel or below.",
      "Drive through the floor to stand back up.",
    ],
    tips: ["Keep chest tall and core braced.", "Push knees out in line with toes."],
    commonMistakes: ["Knees caving inward", "Heels rising", "Forward lean"],
    variants: ["Front Squat", "Goblet Squat", "Bulgarian Split Squat"],
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    category: "back",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "hamstrings", activationType: "primary", intensity: 9 },
      { muscleId: "glutes", activationType: "primary", intensity: 10 },
      { muscleId: "lower-back", activationType: "primary", intensity: 8 },
      { muscleId: "traps", activationType: "secondary", intensity: 6 },
      { muscleId: "lats", activationType: "secondary", intensity: 6 },
      { muscleId: "forearms", activationType: "secondary", intensity: 7 },
    ],
    movementPattern: "hinge",
    difficulty: "advanced",
    instructions: [
      "Stand with feet hip-width apart, bar over mid-foot.",
      "Hinge at hips, bending knees to grip the bar just outside your legs.",
      "Take a deep breath, brace your core, and lift by pushing the floor away.",
      "Lock out hips and knees simultaneously at the top.",
      "Lower the bar under control by hinging at the hips first.",
    ],
    tips: ["Keep bar in contact with your shins throughout.", "Think about 'leg pressing' the floor away."],
    commonMistakes: ["Rounding the back", "Bar drifting away from body", "Jerking the weight off the floor"],
    variants: ["Romanian Deadlift", "Sumo Deadlift", "Trap Bar Deadlift"],
  },
  {
    id: "overhead-press",
    name: "Barbell Overhead Press",
    category: "shoulders",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "front-delts", activationType: "primary", intensity: 10 },
      { muscleId: "triceps", activationType: "secondary", intensity: 7 },
      { muscleId: "traps", activationType: "secondary", intensity: 5 },
      { muscleId: "abs", activationType: "secondary", intensity: 4 },
    ],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Stand with feet shoulder-width apart, bar resting on front delts.",
      "Press the bar overhead while moving head slightly back to clear chin.",
      "Lock out arms at the top, bar directly over the midfoot.",
      "Lower bar back to shoulders under control.",
    ],
    tips: ["Keep glutes and abs tight throughout.", "Push your head through at the top."],
    commonMistakes: ["Excessive lower back arch", "Bar path drifting forward"],
    variants: ["Dumbbell Shoulder Press", "Arnold Press", "Push Press"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    category: "shoulders",
    equipment: ["cable"],
    muscleMap: [
      { muscleId: "front-delts", activationType: "secondary", intensity: 4 },
      { muscleId: "rear-delts", activationType: "primary", intensity: 8 },
    ],
    movementPattern: "isolation",
    difficulty: "beginner",
    instructions: [
      "Stand beside a cable machine, low pulley, single handle.",
      "With a slight forward lean, raise your arm up and out to the side until parallel to the floor.",
      "Lower slowly to starting position.",
    ],
    tips: ["Lead with your elbow, not your hand.", "Keep slight bend in elbow throughout."],
    commonMistakes: ["Using too much weight and swinging", "Shrugging at the top"],
    variants: ["Dumbbell Lateral Raise", "Plate Raise"],
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    category: "arms",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "biceps", activationType: "primary", intensity: 10 },
      { muscleId: "forearms", activationType: "secondary", intensity: 5 },
    ],
    movementPattern: "isolation",
    difficulty: "beginner",
    instructions: [
      "Stand holding a barbell with an underhand grip, shoulder-width apart.",
      "Curl the bar up toward your shoulders, keeping elbows stationary.",
      "Squeeze the biceps at the top.",
      "Lower slowly back to full extension.",
    ],
    tips: ["Don't swing your body — isolate the biceps.", "Fully extend at the bottom for a good stretch."],
    commonMistakes: ["Using momentum and swinging hips", "Not reaching full extension"],
    variants: ["Dumbbell Curl", "Hammer Curl", "Preacher Curl"],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Cable Pushdown",
    category: "arms",
    equipment: ["cable"],
    muscleMap: [
      { muscleId: "triceps", activationType: "primary", intensity: 10 },
    ],
    movementPattern: "isolation",
    difficulty: "beginner",
    instructions: [
      "Stand in front of a high cable pulley with a rope or bar attachment.",
      "Grip the attachment with elbows tucked at your sides.",
      "Push the weight down until arms are fully extended.",
      "Slowly return to starting position.",
    ],
    tips: ["Keep upper arms pinned to your sides.", "Squeeze triceps at full extension."],
    commonMistakes: ["Letting elbows flare out", "Leaning too far forward"],
    variants: ["Skull Crushers", "Overhead Tricep Extension", "Dips"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "legs",
    equipment: ["machine"],
    muscleMap: [
      { muscleId: "quads", activationType: "primary", intensity: 9 },
      { muscleId: "glutes", activationType: "secondary", intensity: 6 },
      { muscleId: "hamstrings", activationType: "secondary", intensity: 4 },
    ],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Sit in the leg press machine with back flat against pad.",
      "Place feet shoulder-width apart on the platform.",
      "Lower the weight until knees are at 90 degrees.",
      "Press the weight back up without locking out knees.",
    ],
    tips: ["Keep lower back pressed into the pad.", "Don't lock knees at the top."],
    commonMistakes: ["Feet placement too low (quad strain)", "Locking out knees"],
    variants: ["Hack Squat", "Front Squat"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    equipment: ["barbell"],
    muscleMap: [
      { muscleId: "hamstrings", activationType: "primary", intensity: 10 },
      { muscleId: "glutes", activationType: "primary", intensity: 8 },
      { muscleId: "lower-back", activationType: "secondary", intensity: 6 },
    ],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Hold a barbell at hip level with overhand grip.",
      "Hinge at hips, pushing them back while lowering bar along your legs.",
      "Feel a deep stretch in hamstrings, bar reaching mid-shin level.",
      "Drive hips forward to return to standing.",
    ],
    tips: ["Keep a slight bend in knees throughout.", "Keep bar close to your legs the entire time."],
    commonMistakes: ["Rounding lower back", "Bending knees too much (becomes a squat)"],
    variants: ["Single Leg RDL", "Dumbbell RDL", "Good Morning"],
  },
  {
    id: "plank",
    name: "Plank",
    category: "core",
    equipment: ["bodyweight"],
    muscleMap: [
      { muscleId: "abs", activationType: "primary", intensity: 9 },
      { muscleId: "obliques", activationType: "secondary", intensity: 5 },
      { muscleId: "lower-back", activationType: "secondary", intensity: 4 },
    ],
    movementPattern: "carry",
    difficulty: "beginner",
    instructions: [
      "Start in a push-up position, then lower onto your forearms.",
      "Keep your body in a straight line from head to heels.",
      "Hold for the prescribed time, breathing normally.",
    ],
    tips: ["Squeeze glutes and abs throughout.", "Don't let hips sag or pike."],
    commonMistakes: ["Hips too high or too low", "Holding breath"],
    variants: ["Side Plank", "Hollow Hold", "Dead Bug"],
  },
  {
    id: "cable-row",
    name: "Seated Cable Row",
    category: "back",
    equipment: ["cable"],
    muscleMap: [
      { muscleId: "lats", activationType: "primary", intensity: 8 },
      { muscleId: "rhomboids", activationType: "primary", intensity: 9 },
      { muscleId: "rear-delts", activationType: "secondary", intensity: 5 },
      { muscleId: "biceps", activationType: "secondary", intensity: 4 },
    ],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Sit at a cable row station, feet on platform, slight bend in knees.",
      "Pull the handle to your lower chest, leading with your elbows.",
      "Squeeze shoulder blades together at contraction.",
      "Slowly extend arms back to starting position.",
    ],
    tips: ["Don't use your lower back to row — keep torso upright.", "Focus on squeezing the shoulder blades."],
    commonMistakes: ["Leaning too far back", "Letting shoulders roll forward at extension"],
    variants: ["Single Arm Cable Row", "Machine Row"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    category: "shoulders",
    equipment: ["cable"],
    muscleMap: [
      { muscleId: "rear-delts", activationType: "primary", intensity: 9 },
      { muscleId: "rhomboids", activationType: "secondary", intensity: 6 },
      { muscleId: "traps", activationType: "secondary", intensity: 5 },
    ],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Set cable pulley to upper chest height with rope attachment.",
      "Pull the rope toward your face, flaring elbows out and up.",
      "Externally rotate at the end — hands at ear level.",
      "Slowly return to starting position.",
    ],
    tips: ["This is a key exercise for shoulder health and rear delt development."],
    commonMistakes: ["Using too much weight", "Not fully externally rotating at peak contraction"],
    variants: ["Band Pull-Apart", "Reverse Fly"],
  },
];

// ─── Workout Templates ────────────────────────────────────────────────────────

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: "ppl-6day",
    name: "Push Pull Legs",
    description: "The classic 6-day hypertrophy split. Excellent for intermediate lifters aiming to build size and strength.",
    splitType: "ppl",
    daysPerWeek: 6,
    estimatedMinutes: 70,
    difficulty: "intermediate",
    equipment: ["barbell", "dumbbell", "cable", "machine"],
    tags: ["hypertrophy", "strength", "6-day", "popular"],
    days: [
      {
        name: "Push A",
        focus: "Chest, Front Delts, Triceps",
        exercises: [
          { exerciseId: "bench-press", sets: 4, repsMin: 6, repsMax: 8, restSeconds: 180 },
          { exerciseId: "incline-dumbbell-press", sets: 3, repsMin: 8, repsMax: 12, restSeconds: 120 },
          { exerciseId: "overhead-press", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120 },
          { exerciseId: "cable-lateral-raise", sets: 4, repsMin: 12, repsMax: 15, restSeconds: 60 },
          { exerciseId: "tricep-pushdown", sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60 },
        ],
      },
      {
        name: "Pull A",
        focus: "Lats, Rhomboids, Biceps",
        exercises: [
          { exerciseId: "pull-up", sets: 4, repsMin: 6, repsMax: 10, restSeconds: 180 },
          { exerciseId: "barbell-row", sets: 4, repsMin: 6, repsMax: 8, restSeconds: 180 },
          { exerciseId: "cable-row", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120 },
          { exerciseId: "face-pull", sets: 3, repsMin: 15, repsMax: 20, restSeconds: 60 },
          { exerciseId: "barbell-curl", sets: 4, repsMin: 10, repsMax: 12, restSeconds: 60 },
        ],
      },
      {
        name: "Legs A",
        focus: "Quads, Hamstrings, Glutes, Calves",
        exercises: [
          { exerciseId: "squat", sets: 4, repsMin: 6, repsMax: 8, restSeconds: 240 },
          { exerciseId: "leg-press", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 180 },
          { exerciseId: "romanian-deadlift", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120 },
        ],
      },
    ],
  },
  {
    id: "upper-lower-4day",
    name: "Upper / Lower Split",
    description: "4-day split alternating upper and lower body. Great for strength and size with good recovery.",
    splitType: "upper-lower",
    daysPerWeek: 4,
    estimatedMinutes: 60,
    difficulty: "intermediate",
    equipment: ["barbell", "dumbbell", "cable"],
    tags: ["strength", "hypertrophy", "4-day", "balanced"],
    days: [
      {
        name: "Upper A",
        focus: "Chest, Back, Shoulders, Arms",
        exercises: [
          { exerciseId: "bench-press", sets: 4, repsMin: 5, repsMax: 8, restSeconds: 180 },
          { exerciseId: "barbell-row", sets: 4, repsMin: 5, repsMax: 8, restSeconds: 180 },
          { exerciseId: "overhead-press", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120 },
          { exerciseId: "pull-up", sets: 3, repsMin: 6, repsMax: 10, restSeconds: 120 },
          { exerciseId: "barbell-curl", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60 },
          { exerciseId: "tricep-pushdown", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 60 },
        ],
      },
      {
        name: "Lower A",
        focus: "Quads, Hamstrings, Glutes",
        exercises: [
          { exerciseId: "squat", sets: 4, repsMin: 5, repsMax: 8, restSeconds: 240 },
          { exerciseId: "romanian-deadlift", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 180 },
          { exerciseId: "leg-press", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 120 },
          { exerciseId: "plank", sets: 3, repsMin: 30, repsMax: 60, restSeconds: 60, notes: "Hold for reps value in seconds" },
        ],
      },
    ],
  },
  {
    id: "full-body-3day",
    name: "Full Body 3-Day",
    description: "Three full-body sessions per week. Ideal for beginners and those short on time.",
    splitType: "full-body",
    daysPerWeek: 3,
    estimatedMinutes: 50,
    difficulty: "beginner",
    equipment: ["barbell", "dumbbell"],
    tags: ["beginner-friendly", "full-body", "3-day", "efficient"],
    days: [
      {
        name: "Full Body A",
        focus: "Compound lifts — all muscle groups",
        exercises: [
          { exerciseId: "squat", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 180 },
          { exerciseId: "bench-press", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120 },
          { exerciseId: "barbell-row", sets: 3, repsMin: 8, repsMax: 10, restSeconds: 120 },
          { exerciseId: "overhead-press", sets: 2, repsMin: 10, repsMax: 12, restSeconds: 90 },
          { exerciseId: "plank", sets: 3, repsMin: 30, repsMax: 45, restSeconds: 60 },
        ],
      },
    ],
  },
  {
    id: "beginner-3day",
    name: "Beginner Strength 3-Day",
    description: "A linear progression program designed for beginners. Focus on mastering compound movements.",
    splitType: "beginner-3day",
    daysPerWeek: 3,
    estimatedMinutes: 45,
    difficulty: "beginner",
    equipment: ["barbell"],
    tags: ["beginner", "strength", "linear-progression", "3-day"],
    days: [
      {
        name: "Workout A",
        focus: "Squat, Bench, Row",
        exercises: [
          { exerciseId: "squat", sets: 3, repsMin: 5, repsMax: 5, restSeconds: 180 },
          { exerciseId: "bench-press", sets: 3, repsMin: 5, repsMax: 5, restSeconds: 120 },
          { exerciseId: "barbell-row", sets: 3, repsMin: 5, repsMax: 5, restSeconds: 120 },
        ],
      },
      {
        name: "Workout B",
        focus: "Squat, OHP, Deadlift",
        exercises: [
          { exerciseId: "squat", sets: 3, repsMin: 5, repsMax: 5, restSeconds: 180 },
          { exerciseId: "overhead-press", sets: 3, repsMin: 5, repsMax: 5, restSeconds: 120 },
          { exerciseId: "deadlift", sets: 1, repsMin: 5, repsMax: 5, restSeconds: 300 },
        ],
      },
    ],
  },
  {
    id: "dumbbell-only",
    name: "Dumbbell Only",
    description: "Full-body dumbbell routine — perfect for home gyms or hotel workouts.",
    splitType: "full-body",
    daysPerWeek: 3,
    estimatedMinutes: 45,
    difficulty: "beginner",
    equipment: ["dumbbell"],
    tags: ["home-gym", "dumbbell", "travel", "beginner"],
    days: [
      {
        name: "Session A",
        focus: "Chest, Back, Shoulders",
        exercises: [
          { exerciseId: "incline-dumbbell-press", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90 },
          { exerciseId: "cable-row", sets: 3, repsMin: 10, repsMax: 12, restSeconds: 90, notes: "Use dumbbell row" },
          { exerciseId: "cable-lateral-raise", sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60 },
          { exerciseId: "barbell-curl", sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60 },
          { exerciseId: "tricep-pushdown", sets: 3, repsMin: 12, repsMax: 15, restSeconds: 60 },
        ],
      },
    ],
  },
];

// ─── Session History (past 4 weeks) ──────────────────────────────────────────

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);

export const SESSION_HISTORY: WorkoutSession[] = [
  {
    id: "session-1",
    templateId: "ppl-6day",
    name: "Push A",
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    durationMinutes: 68,
    totalVolume: 12840,
    exercises: [
      {
        id: "se-1",
        exerciseId: "bench-press",
        order: 1,
        sets: [
          { id: "s1", setNumber: 1, weight: 100, reps: 5, isWarmup: true, completedAt: daysAgo(1) },
          { id: "s2", setNumber: 2, weight: 120, reps: 7, isWarmup: false, rpe: 8, completedAt: daysAgo(1) },
          { id: "s3", setNumber: 3, weight: 120, reps: 7, isWarmup: false, rpe: 8, completedAt: daysAgo(1) },
          { id: "s4", setNumber: 4, weight: 120, reps: 6, isWarmup: false, rpe: 9, completedAt: daysAgo(1) },
          { id: "s5", setNumber: 5, weight: 115, reps: 7, isWarmup: false, rpe: 8, completedAt: daysAgo(1) },
        ],
      },
      {
        id: "se-2",
        exerciseId: "incline-dumbbell-press",
        order: 2,
        sets: [
          { id: "s6", setNumber: 1, weight: 36, reps: 10, isWarmup: false, completedAt: daysAgo(1) },
          { id: "s7", setNumber: 2, weight: 36, reps: 10, isWarmup: false, completedAt: daysAgo(1) },
          { id: "s8", setNumber: 3, weight: 36, reps: 9, isWarmup: false, completedAt: daysAgo(1) },
        ],
      },
      {
        id: "se-3",
        exerciseId: "overhead-press",
        order: 3,
        sets: [
          { id: "s9", setNumber: 1, weight: 70, reps: 9, isWarmup: false, completedAt: daysAgo(1) },
          { id: "s10", setNumber: 2, weight: 70, reps: 8, isWarmup: false, completedAt: daysAgo(1) },
          { id: "s11", setNumber: 3, weight: 70, reps: 7, isWarmup: false, completedAt: daysAgo(1) },
        ],
      },
    ],
  },
  {
    id: "session-2",
    templateId: "ppl-6day",
    name: "Pull A",
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    durationMinutes: 65,
    totalVolume: 9640,
    exercises: [
      {
        id: "se-4",
        exerciseId: "pull-up",
        order: 1,
        sets: [
          { id: "s12", setNumber: 1, weight: 0, reps: 9, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s13", setNumber: 2, weight: 0, reps: 8, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s14", setNumber: 3, weight: 0, reps: 7, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s15", setNumber: 4, weight: 0, reps: 6, isWarmup: false, completedAt: daysAgo(2) },
        ],
      },
      {
        id: "se-5",
        exerciseId: "barbell-row",
        order: 2,
        sets: [
          { id: "s16", setNumber: 1, weight: 95, reps: 8, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s17", setNumber: 2, weight: 95, reps: 8, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s18", setNumber: 3, weight: 95, reps: 7, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s19", setNumber: 4, weight: 90, reps: 8, isWarmup: false, completedAt: daysAgo(2) },
        ],
      },
      {
        id: "se-6",
        exerciseId: "barbell-curl",
        order: 3,
        sets: [
          { id: "s20", setNumber: 1, weight: 45, reps: 12, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s21", setNumber: 2, weight: 45, reps: 11, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s22", setNumber: 3, weight: 45, reps: 10, isWarmup: false, completedAt: daysAgo(2) },
          { id: "s23", setNumber: 4, weight: 42.5, reps: 12, isWarmup: false, completedAt: daysAgo(2) },
        ],
      },
    ],
  },
  {
    id: "session-3",
    templateId: "ppl-6day",
    name: "Legs A",
    startedAt: daysAgo(3),
    completedAt: daysAgo(3),
    durationMinutes: 75,
    totalVolume: 18200,
    exercises: [
      {
        id: "se-7",
        exerciseId: "squat",
        order: 1,
        sets: [
          { id: "s24", setNumber: 1, weight: 120, reps: 5, isWarmup: true, completedAt: daysAgo(3) },
          { id: "s25", setNumber: 2, weight: 145, reps: 7, isWarmup: false, rpe: 8, completedAt: daysAgo(3) },
          { id: "s26", setNumber: 3, weight: 145, reps: 6, isWarmup: false, rpe: 9, completedAt: daysAgo(3) },
          { id: "s27", setNumber: 4, weight: 145, reps: 6, isWarmup: false, rpe: 9, completedAt: daysAgo(3) },
        ],
      },
      {
        id: "se-8",
        exerciseId: "leg-press",
        order: 2,
        sets: [
          { id: "s28", setNumber: 1, weight: 200, reps: 12, isWarmup: false, completedAt: daysAgo(3) },
          { id: "s29", setNumber: 2, weight: 200, reps: 11, isWarmup: false, completedAt: daysAgo(3) },
          { id: "s30", setNumber: 3, weight: 200, reps: 10, isWarmup: false, completedAt: daysAgo(3) },
        ],
      },
      {
        id: "se-9",
        exerciseId: "romanian-deadlift",
        order: 3,
        sets: [
          { id: "s31", setNumber: 1, weight: 90, reps: 10, isWarmup: false, completedAt: daysAgo(3) },
          { id: "s32", setNumber: 2, weight: 90, reps: 10, isWarmup: false, completedAt: daysAgo(3) },
          { id: "s33", setNumber: 3, weight: 90, reps: 9, isWarmup: false, completedAt: daysAgo(3) },
        ],
      },
    ],
  },
];

// ─── Personal Records ─────────────────────────────────────────────────────────

export const PERSONAL_RECORDS: PersonalRecord[] = [
  {
    exerciseId: "bench-press",
    exerciseName: "Barbell Bench Press",
    weight: 125,
    reps: 5,
    estimatedOneRepMax: 141,
    achievedAt: daysAgo(7),
  },
  {
    exerciseId: "squat",
    exerciseName: "Barbell Back Squat",
    weight: 150,
    reps: 5,
    estimatedOneRepMax: 169,
    achievedAt: daysAgo(10),
  },
  {
    exerciseId: "deadlift",
    exerciseName: "Conventional Deadlift",
    weight: 180,
    reps: 3,
    estimatedOneRepMax: 191,
    achievedAt: daysAgo(14),
  },
  {
    exerciseId: "overhead-press",
    exerciseName: "Barbell Overhead Press",
    weight: 75,
    reps: 5,
    estimatedOneRepMax: 85,
    achievedAt: daysAgo(5),
  },
];

// ─── Mock User Profile ────────────────────────────────────────────────────────

export const MOCK_USER: UserProfile = {
  id: "user-1",
  name: "Alex Johnson",
  displayName: "Alex",
  email: "alex@example.com",
  goal: "build-muscle",
  experienceLevel: "intermediate",
  gymType: "commercial",
  workoutsPerWeek: 5,
  availableEquipment: ["barbell", "dumbbell", "cable", "machine"],
  preferredSplit: "ppl",
  weightKg: 82,
  heightCm: 178,
  joinedAt: new Date("2024-01-15"),
  currentStreak: 8,
  longestStreak: 23,
  totalSessions: 142,
  totalVolumeKg: 245680,
};

// ─── Muscle Activation State ──────────────────────────────────────────────────

export const MOCK_MUSCLE_ACTIVATIONS: MuscleActivation[] = [
  { muscleId: "chest", score: 75, level: "heavy", lastTrained: daysAgo(1), weeklySets: 10 },
  { muscleId: "front-delts", score: 70, level: "heavy", lastTrained: daysAgo(1), weeklySets: 9 },
  { muscleId: "triceps", score: 60, level: "moderate", lastTrained: daysAgo(1), weeklySets: 7 },
  { muscleId: "lats", score: 65, level: "moderate", lastTrained: daysAgo(2), weeklySets: 12 },
  { muscleId: "biceps", score: 55, level: "moderate", lastTrained: daysAgo(2), weeklySets: 8 },
  { muscleId: "rhomboids", score: 60, level: "moderate", lastTrained: daysAgo(2), weeklySets: 8 },
  { muscleId: "rear-delts", score: 45, level: "light", lastTrained: daysAgo(2), weeklySets: 6 },
  { muscleId: "quads", score: 85, level: "recovering", lastTrained: daysAgo(3), weeklySets: 10 },
  { muscleId: "hamstrings", score: 80, level: "recovering", lastTrained: daysAgo(3), weeklySets: 6 },
  { muscleId: "glutes", score: 78, level: "recovering", lastTrained: daysAgo(3), weeklySets: 7 },
  { muscleId: "abs", score: 20, level: "fresh", lastTrained: daysAgo(8), weeklySets: 0 },
  { muscleId: "obliques", score: 15, level: "fresh", lastTrained: daysAgo(8), weeklySets: 0 },
  { muscleId: "calves", score: 10, level: "fresh", lastTrained: daysAgo(10), weeklySets: 0 },
  { muscleId: "traps", score: 30, level: "light", lastTrained: daysAgo(2), weeklySets: 4 },
  { muscleId: "forearms", score: 40, level: "light", lastTrained: daysAgo(2), weeklySets: 5 },
  { muscleId: "lower-back", score: 35, level: "light", lastTrained: daysAgo(3), weeklySets: 4 },
];

// ─── Muscle Details ───────────────────────────────────────────────────────────

export const MUSCLE_DETAILS: Record<string, MuscleDetail> = {
  chest: {
    muscleId: "chest",
    displayName: "Chest (Pectoralis Major)",
    lastTrained: daysAgo(1),
    weeklySets: 10,
    recoveryPercent: 35,
    recommendedExercises: ["Barbell Bench Press", "Incline Dumbbell Press", "Cable Fly"],
  },
  "front-delts": {
    muscleId: "front-delts",
    displayName: "Front Deltoids",
    lastTrained: daysAgo(1),
    weeklySets: 9,
    recoveryPercent: 40,
    recommendedExercises: ["Overhead Press", "Arnold Press", "Front Raise"],
  },
  lats: {
    muscleId: "lats",
    displayName: "Latissimus Dorsi",
    lastTrained: daysAgo(2),
    weeklySets: 12,
    recoveryPercent: 55,
    recommendedExercises: ["Pull-Up", "Lat Pulldown", "Barbell Row"],
  },
  quads: {
    muscleId: "quads",
    displayName: "Quadriceps",
    lastTrained: daysAgo(3),
    weeklySets: 10,
    recoveryPercent: 20,
    recommendedExercises: ["Back Squat", "Leg Press", "Hack Squat"],
  },
  hamstrings: {
    muscleId: "hamstrings",
    displayName: "Hamstrings",
    lastTrained: daysAgo(3),
    weeklySets: 6,
    recoveryPercent: 25,
    recommendedExercises: ["Romanian Deadlift", "Lying Leg Curl", "Nordic Curl"],
  },
  glutes: {
    muscleId: "glutes",
    displayName: "Glutes (Gluteus Maximus)",
    lastTrained: daysAgo(3),
    weeklySets: 7,
    recoveryPercent: 28,
    recommendedExercises: ["Hip Thrust", "Romanian Deadlift", "Bulgarian Split Squat"],
  },
  abs: {
    muscleId: "abs",
    displayName: "Abdominals",
    lastTrained: daysAgo(8),
    weeklySets: 0,
    recoveryPercent: 100,
    recommendedExercises: ["Plank", "Hanging Leg Raise", "Ab Wheel Rollout"],
  },
  calves: {
    muscleId: "calves",
    displayName: "Calves (Gastrocnemius)",
    lastTrained: daysAgo(10),
    weeklySets: 0,
    recoveryPercent: 100,
    recommendedExercises: ["Standing Calf Raise", "Seated Calf Raise"],
  },
  biceps: {
    muscleId: "biceps",
    displayName: "Biceps",
    lastTrained: daysAgo(2),
    weeklySets: 8,
    recoveryPercent: 60,
    recommendedExercises: ["Barbell Curl", "Dumbbell Curl", "Hammer Curl"],
  },
  triceps: {
    muscleId: "triceps",
    displayName: "Triceps",
    lastTrained: daysAgo(1),
    weeklySets: 7,
    recoveryPercent: 45,
    recommendedExercises: ["Tricep Pushdown", "Skull Crushers", "Dips"],
  },
  "rear-delts": {
    muscleId: "rear-delts",
    displayName: "Rear Deltoids",
    lastTrained: daysAgo(2),
    weeklySets: 6,
    recoveryPercent: 65,
    recommendedExercises: ["Face Pull", "Reverse Fly", "Band Pull-Apart"],
  },
  traps: {
    muscleId: "traps",
    displayName: "Trapezius",
    lastTrained: daysAgo(2),
    weeklySets: 4,
    recoveryPercent: 70,
    recommendedExercises: ["Barbell Shrug", "Face Pull", "Deadlift"],
  },
  rhomboids: {
    muscleId: "rhomboids",
    displayName: "Rhomboids",
    lastTrained: daysAgo(2),
    weeklySets: 8,
    recoveryPercent: 55,
    recommendedExercises: ["Barbell Row", "Cable Row", "Face Pull"],
  },
  obliques: {
    muscleId: "obliques",
    displayName: "Obliques",
    lastTrained: daysAgo(8),
    weeklySets: 0,
    recoveryPercent: 100,
    recommendedExercises: ["Side Plank", "Pallof Press", "Cable Woodchop"],
  },
  "lower-back": {
    muscleId: "lower-back",
    displayName: "Lower Back (Erectors)",
    lastTrained: daysAgo(3),
    weeklySets: 4,
    recoveryPercent: 68,
    recommendedExercises: ["Good Morning", "Hyperextension", "Deadlift"],
  },
  forearms: {
    muscleId: "forearms",
    displayName: "Forearms",
    lastTrained: daysAgo(2),
    weeklySets: 5,
    recoveryPercent: 72,
    recommendedExercises: ["Barbell Wrist Curl", "Farmer's Walk", "Dead Hang"],
  },
};

// ─── Progress / Analytics Data ────────────────────────────────────────────────

export const VOLUME_HISTORY: VolumeDataPoint[] = Array.from({ length: 8 }, (_, i) => ({
  date: new Date(now.getTime() - (7 - i) * 7 * 86400000).toLocaleDateString("en-US", { month: "short", day: "numeric" }),
  volume: Math.round(8000 + Math.random() * 6000),
  sessions: Math.round(3 + Math.random() * 3),
}));

export const BENCH_PROGRESS: LiftProgressPoint[] = [
  { date: "Jan 1", weight: 100, reps: 5, estimatedOneRM: 113 },
  { date: "Jan 8", weight: 102.5, reps: 5, estimatedOneRM: 115 },
  { date: "Jan 15", weight: 105, reps: 5, estimatedOneRM: 118 },
  { date: "Jan 22", weight: 107.5, reps: 5, estimatedOneRM: 121 },
  { date: "Feb 1", weight: 110, reps: 5, estimatedOneRM: 124 },
  { date: "Feb 8", weight: 112.5, reps: 6, estimatedOneRM: 130 },
  { date: "Feb 15", weight: 115, reps: 6, estimatedOneRM: 133 },
  { date: "Feb 22", weight: 117.5, reps: 6, estimatedOneRM: 136 },
  { date: "Mar 1", weight: 120, reps: 7, estimatedOneRM: 141 },
  { date: "Mar 8", weight: 122.5, reps: 6, estimatedOneRM: 142 },
  { date: "Mar 15", weight: 120, reps: 8, estimatedOneRM: 143 },
  { date: "Mar 22", weight: 125, reps: 5, estimatedOneRM: 141 },
];

export const SQUAT_PROGRESS: LiftProgressPoint[] = [
  { date: "Jan 1", weight: 120, reps: 5, estimatedOneRM: 135 },
  { date: "Jan 8", weight: 122.5, reps: 5, estimatedOneRM: 138 },
  { date: "Jan 15", weight: 125, reps: 5, estimatedOneRM: 141 },
  { date: "Jan 22", weight: 127.5, reps: 6, estimatedOneRM: 148 },
  { date: "Feb 1", weight: 130, reps: 6, estimatedOneRM: 151 },
  { date: "Feb 8", weight: 132.5, reps: 5, estimatedOneRM: 149 },
  { date: "Feb 15", weight: 135, reps: 5, estimatedOneRM: 152 },
  { date: "Feb 22", weight: 140, reps: 5, estimatedOneRM: 158 },
  { date: "Mar 1", weight: 142.5, reps: 6, estimatedOneRM: 165 },
  { date: "Mar 8", weight: 145, reps: 6, estimatedOneRM: 168 },
  { date: "Mar 15", weight: 147.5, reps: 5, estimatedOneRM: 166 },
  { date: "Mar 22", weight: 150, reps: 5, estimatedOneRM: 169 },
];

export const MUSCLE_VOLUME_DATA: MuscleVolumeData[] = [
  { muscleId: "chest", muscleName: "Chest", weeklySets: 10, weeklyVolume: 4800 },
  { muscleId: "lats", muscleName: "Lats", weeklySets: 12, weeklyVolume: 3200 },
  { muscleId: "quads", muscleName: "Quads", weeklySets: 10, weeklyVolume: 5600 },
  { muscleId: "hamstrings", muscleName: "Hamstrings", weeklySets: 6, weeklyVolume: 2160 },
  { muscleId: "front-delts", muscleName: "Front Delts", weeklySets: 9, weeklyVolume: 1890 },
  { muscleId: "biceps", muscleName: "Biceps", weeklySets: 8, weeklyVolume: 1440 },
  { muscleId: "triceps", muscleName: "Triceps", weeklySets: 7, weeklyVolume: 980 },
  { muscleId: "abs", muscleName: "Abs", weeklySets: 0, weeklyVolume: 0 },
  { muscleId: "calves", muscleName: "Calves", weeklySets: 0, weeklyVolume: 0 },
];

// ─── Recommendations ──────────────────────────────────────────────────────────

export const TRAINING_RECOMMENDATIONS: TrainingRecommendation[] = [
  {
    type: "recover",
    muscleIds: ["quads", "hamstrings", "glutes"],
    message: "Legs are still recovering from yesterday's session. Train Push or Pull today.",
  },
  {
    type: "train",
    muscleIds: ["abs", "calves"],
    message: "Abs and calves are fully fresh — ideal time to add accessory work.",
  },
  {
    type: "progress",
    muscleIds: ["chest"],
    message: "You're ready to progress the Bench Press next Push session. Add 2.5kg.",
  },
];
